name: Go Linter
on: [push, pull_request]
jobs:
  go_linter:
    runs-on: windows-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Download Dependencies
        run: go get -v -t -d ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
